server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 192.168.139.128:8848
    gateway:
      enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: shop-service
          uri: lb://shop-service
          predicates:
            - Path= /shop/**, /shop-type/**

        - id: voucher-service
          uri: lb://voucher-service
          predicates:
            - Path=/voucher/**, /voucher-order/**
        - id: follow-service
          uri: lb://follow-service
          predicates:
            - Path=/follow/**
        - id: blog-service
          uri: lb://blog-service
          predicates:
            - Path=/blog-comments/**, /blog/**

